/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTranslateRouteImport } from './routes/_authenticated/translate'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedPresentationRouteImport } from './routes/_authenticated/presentation'
import { Route as AuthenticatedPdfRouteImport } from './routes/_authenticated/pdf'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedImageRouteImport } from './routes/_authenticated/image'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated/cover-letter'
import { Route as AuthenticatedCodeRouteImport } from './routes/_authenticated/code'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTranslateRoute = AuthenticatedTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresentationRoute =
  AuthenticatedPresentationRouteImport.update({
    id: '/presentation',
    path: '/presentation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPdfRoute = AuthenticatedPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageRoute = AuthenticatedImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCodeRoute = AuthenticatedCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/code': typeof AuthenticatedCodeRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/image': typeof AuthenticatedImageRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/pdf': typeof AuthenticatedPdfRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/translate': typeof AuthenticatedTranslateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/chat': typeof AuthenticatedChatRoute
  '/code': typeof AuthenticatedCodeRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/image': typeof AuthenticatedImageRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/pdf': typeof AuthenticatedPdfRoute
  '/presentation': typeof AuthenticatedPresentationRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/translate': typeof AuthenticatedTranslateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/code': typeof AuthenticatedCodeRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/image': typeof AuthenticatedImageRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/pdf': typeof AuthenticatedPdfRoute
  '/_authenticated/presentation': typeof AuthenticatedPresentationRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/translate': typeof AuthenticatedTranslateRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/admin'
    | '/chat'
    | '/code'
    | '/cover-letter'
    | '/dashboard'
    | '/image'
    | '/notes'
    | '/pdf'
    | '/presentation'
    | '/resume'
    | '/translate'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/admin'
    | '/chat'
    | '/code'
    | '/cover-letter'
    | '/dashboard'
    | '/image'
    | '/notes'
    | '/pdf'
    | '/presentation'
    | '/resume'
    | '/translate'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/_authenticated/admin'
    | '/_authenticated/chat'
    | '/_authenticated/code'
    | '/_authenticated/cover-letter'
    | '/_authenticated/dashboard'
    | '/_authenticated/image'
    | '/_authenticated/notes'
    | '/_authenticated/pdf'
    | '/_authenticated/presentation'
    | '/_authenticated/resume'
    | '/_authenticated/translate'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/translate': {
      id: '/_authenticated/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof AuthenticatedTranslateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presentation': {
      id: '/_authenticated/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof AuthenticatedPresentationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdf': {
      id: '/_authenticated/pdf'
      path: '/pdf'
      fullPath: '/pdf'
      preLoaderRoute: typeof AuthenticatedPdfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image': {
      id: '/_authenticated/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof AuthenticatedImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/code': {
      id: '/_authenticated/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AuthenticatedCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCodeRoute: typeof AuthenticatedCodeRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedImageRoute: typeof AuthenticatedImageRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPdfRoute: typeof AuthenticatedPdfRoute
  AuthenticatedPresentationRoute: typeof AuthenticatedPresentationRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedTranslateRoute: typeof AuthenticatedTranslateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCodeRoute: AuthenticatedCodeRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedImageRoute: AuthenticatedImageRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPdfRoute: AuthenticatedPdfRoute,
  AuthenticatedPresentationRoute: AuthenticatedPresentationRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedTranslateRoute: AuthenticatedTranslateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
